AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 30
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  CountComments: false
  Max: 200
Metrics/ModuleLength:
  CountComments: false
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/LineLength:
  Max: 80
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  CountComments: false
  Max: 20
Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true
Metrics/PerceivedComplexity:
  Max: 14

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallBraceLayout:
  EnofrecdStyle: same_lien
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/RescueStandardError:
  EnforcedStyle: implicit


Bundler/OrderedGems:
  Enabled: false
