AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# double size metrics
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
  AllowedMethods:
    - refine
    - configure
  Exclude:
    - spec/**/*_spec.rb
    - Rakefile
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 14

Naming/MethodParameterName:
  AllowedNames:
    - at
    - by
    - db
    - id
    - in
    - io
    - ip
    - of
    - 'on'
    - os
    - pp
    - to
    - dn

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  AllowBracesOnProceduralOneLiners: true
  BracesRequiredMethods: ['let']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatString:
  EnforcedStyle: percent
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 7
Style/OneLineConditional:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/SymbolArray:
  MinSize: 8
Style/WordArray:
  MinSize: 8
Style/DoubleNegation:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*_spec.rb
# applications

Bundler/OrderedGems:
  Enabled: false

