require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/LineLength:
  Max: 80
  Exclude:
    - spec/**/*_spec.rb
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/Void:
  Enabled: false

# double size metrics
Metrics/AbcSize:
  Max: 30
  AllowedMethods:
    - call
  Exclude:
    - spec/support/*.rb
Metrics/BlockLength:
  Max: 50
  AllowedMethods:
    - refine
    - configure
  Exclude:
    - spec/**/*_spec.rb
    - Rakefile
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 12
  AllowedMethods:
    - call
Metrics/MethodLength:
  Max: 20
  AllowedMethods:
    - call
  Exclude:
    - spec/support/*.rb
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 14
  AllowedMethods:
    - call

Naming/MethodParameterName:
  AllowedNames:
    - at
    - by
    - db
    - id
    - in
    - io
    - ip
    - of
    - 'on'
    - os
    - pp
    - to
    - dn
Naming/PredicateName:
  ForbiddenPrefixes: 
    - is_

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  AllowBracesOnProceduralOneLiners: true
  BracesRequiredMethods: ['let']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatString:
  EnforcedStyle: percent
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/Lambda:
  EnforcedStyle: literal
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 7
Style/OneLineConditional:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/SymbolArray:
  MinSize: 8
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/WordArray:
  MinSize: 8
Style/DoubleNegation:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*_spec.rb
# applications

Bundler/OrderedGems:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/SpecFilePathFormat:
  IgnoreMethods: true
  CustomTransform:
    Yuzakan: .
