AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true

# 0.80
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# 0.81
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

# 0.82
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

# double size metrics
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*_spec.rb
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 14

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/NumericLiterals:
  MinDigits: 7
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/SymbolArray:
  MinSize: 8
Style/WordArray:
  MinSize: 8
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/OneLineConditional:
  AlwaysCorrectToMultiline: true

# applications

Bundler/OrderedGems:
  Enabled: false
