AllCops:
  TargetRubyVersion: 2.5

# 0.80
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# 0.81
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

# 0.82
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true

Layout/LineLength:
  Max: 80

# double size metrics
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
Metrics/BlockNesting:
  Max: 6
  Exclude:
    - spec/**/*_spec.rb
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 14

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SymbolArray:
  MinSize: 8
Style/EmptyMethod:
  EnforcedStyle: expanded

Bundler/OrderedGems:
  Enabled: false
