type SvgProps<S, C> = CustomPayloads<S, C> & Props<S>;
type SvgChildren<S> = MaybeVNode<S> | readonly MaybeVNode<S>[];
type SvgTag = <S, C = unknown>(props?: SvgProps<S, C> | SvgChildren<S>,
  children?: SvgChildren<S>) => ElementVNode<S>;

declare module '@hyperapp/svg' {
  const a: SvgTag;
  const g: SvgTag;
  const svg: SvgTag;
  const use: SvgTag;
  const set: SvgTag;
  const line: SvgTag;
  const path: SvgTag;
  const rect: SvgTag;
  const desc: SvgTag;
  const defs: SvgTag;
  const mask: SvgTag;
  const tref: SvgTag;
  const font: SvgTag;
  const stop: SvgTag;
  const view: SvgTag;
  const text_: SvgTag;
  const image: SvgTag;
  const mpath: SvgTag;
  const title: SvgTag;
  const glyph: SvgTag;
  const tspan: SvgTag;
  const style: SvgTag;
  const circle: SvgTag;
  const marker: SvgTag;
  const symbol: SvgTag;
  const feTile: SvgTag;
  const cursor: SvgTag;
  const filter: SvgTag;
  const switch_: SvgTag;
  const ellipse: SvgTag;
  const polygon: SvgTag;
  const animate: SvgTag;
  const pattern: SvgTag;
  const feBlend: SvgTag;
  const feFlood: SvgTag;
  const feFuncA: SvgTag;
  const feFuncB: SvgTag;
  const feFuncG: SvgTag;
  const feFuncR: SvgTag;
  const feImage: SvgTag;
  const feMerge: SvgTag;
  const polyline: SvgTag;
  const metadata: SvgTag;
  const altGlyph: SvgTag;
  const glyphRef: SvgTag;
  const textPath: SvgTag;
  const feOffset: SvgTag;
  const clipPath: SvgTag;
  const altGlyphDef: SvgTag;
  const feComposite: SvgTag;
  const feMergeNode: SvgTag;
  const feSpotLight: SvgTag;
  const animateColor: SvgTag;
  const altGlyphItem: SvgTag;
  const feMorphology: SvgTag;
  const feTurbulence: SvgTag;
  const fePointLight: SvgTag;
  const colorProfile: SvgTag;
  const foreignObject: SvgTag;
  const animateMotion: SvgTag;
  const feColorMatrix: SvgTag;
  const linearGradient: SvgTag;
  const radialGradient: SvgTag;
  const feGaussianBlur: SvgTag;
  const feDistantLight: SvgTag;
  const animateTransform: SvgTag;
  const feConvolveMatrix: SvgTag;
  const feDiffuseLighting: SvgTag;
  const feDisplacementMap: SvgTag;
  const feSpecularLighting: SvgTag;
  const feComponentTransfer: SvgTag;
}
