--
-- PostgreSQL database dump
--

\restrict jztKIliamzEmtrAU9sP3dWqd3wbacnX1r3d3Y7VOxExBEAKSknTJb8oMinxuxYd

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: action_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.action_logs (
    id integer NOT NULL,
    uuid text NOT NULL,
    client text NOT NULL,
    "user" text NOT NULL,
    action text NOT NULL,
    method text NOT NULL,
    path text NOT NULL,
    status integer,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: action_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.action_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.action_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: affiliations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.affiliations (
    id integer NOT NULL,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: affiliations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.affiliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.affiliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attrs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attrs (
    id integer NOT NULL,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    category text NOT NULL,
    type text NOT NULL,
    "order" integer NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    readonly boolean DEFAULT false NOT NULL,
    code text DEFAULT ''::text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: attrs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attrs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_logs (
    id integer NOT NULL,
    uuid text NOT NULL,
    client text NOT NULL,
    "user" text NOT NULL,
    type text NOT NULL,
    result text NOT NULL,
    service text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: auth_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configs (
    id integer NOT NULL,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    domain text DEFAULT ''::text NOT NULL,
    session_timeout integer DEFAULT 3600 NOT NULL,
    auth_failure_waiting integer DEFAULT 2 NOT NULL,
    auth_failure_limit integer DEFAULT 5 NOT NULL,
    auth_failure_duration integer DEFAULT 600 NOT NULL,
    password_min_size integer DEFAULT 8 NOT NULL,
    password_max_size integer DEFAULT 64 NOT NULL,
    password_min_types integer DEFAULT 1 NOT NULL,
    password_prohibited_chars text DEFAULT ''::text NOT NULL,
    password_min_score integer DEFAULT 0 NOT NULL,
    password_extra_dict text[] DEFAULT ARRAY[]::text[] NOT NULL,
    generate_password_size integer DEFAULT 24 NOT NULL,
    generate_password_type text DEFAULT 'ascii'::text NOT NULL,
    generate_password_chars text DEFAULT ' '::text NOT NULL,
    contact_name text DEFAULT ''::text NOT NULL,
    contact_email text DEFAULT ''::text NOT NULL,
    contact_phone text DEFAULT ''::text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dictionaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dictionaries (
    id integer NOT NULL,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: dictionaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dictionaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dictionaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups (
    id integer NOT NULL,
    affiliation_id integer,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    basic boolean DEFAULT false NOT NULL,
    prohibited boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: local_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.local_groups (
    id integer NOT NULL,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    attrs jsonb NOT NULL
);


--
-- Name: local_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.local_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.local_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: local_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.local_members (
    id integer NOT NULL,
    local_user_id integer NOT NULL,
    local_group_id integer NOT NULL
);


--
-- Name: local_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.local_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.local_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: local_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.local_users (
    id integer NOT NULL,
    local_group_id integer,
    name text NOT NULL,
    hashed_password text DEFAULT ''::text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    email text DEFAULT ''::text NOT NULL,
    locked boolean DEFAULT false NOT NULL,
    attrs jsonb NOT NULL
);


--
-- Name: local_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.local_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.local_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mappings (
    id integer NOT NULL,
    attr_id integer NOT NULL,
    service_id integer NOT NULL,
    key text NOT NULL,
    type text NOT NULL,
    params jsonb,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: networks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.networks (
    id integer NOT NULL,
    ip cidr NOT NULL,
    clearance_level integer DEFAULT 1 NOT NULL,
    trusted boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: networks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.networks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.networks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services (
    id integer NOT NULL,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    "order" integer NOT NULL,
    adapter text NOT NULL,
    params jsonb NOT NULL,
    readable boolean DEFAULT false NOT NULL,
    writable boolean DEFAULT false NOT NULL,
    authenticatable boolean DEFAULT false NOT NULL,
    password_changeable boolean DEFAULT false NOT NULL,
    lockable boolean DEFAULT false NOT NULL,
    "group" boolean DEFAULT false NOT NULL,
    individual_password boolean DEFAULT false NOT NULL,
    self_management boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terms (
    id integer NOT NULL,
    dictionary_id integer NOT NULL,
    term text NOT NULL,
    description text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: terms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    affiliation_id integer,
    group_id integer,
    name text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    email text DEFAULT ''::text NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    clearance_level integer DEFAULT 1 NOT NULL,
    prohibited boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: action_logs action_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_logs
    ADD CONSTRAINT action_logs_pkey PRIMARY KEY (id);


--
-- Name: affiliations affiliations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliations
    ADD CONSTRAINT affiliations_pkey PRIMARY KEY (id);


--
-- Name: attrs attrs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attrs
    ADD CONSTRAINT attrs_pkey PRIMARY KEY (id);


--
-- Name: auth_logs auth_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_logs
    ADD CONSTRAINT auth_logs_pkey PRIMARY KEY (id);


--
-- Name: configs configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configs
    ADD CONSTRAINT configs_pkey PRIMARY KEY (id);


--
-- Name: dictionaries dictionaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dictionaries
    ADD CONSTRAINT dictionaries_pkey PRIMARY KEY (id);


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- Name: local_groups local_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_groups
    ADD CONSTRAINT local_groups_pkey PRIMARY KEY (id);


--
-- Name: local_members local_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_members
    ADD CONSTRAINT local_members_pkey PRIMARY KEY (id);


--
-- Name: local_users local_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_users
    ADD CONSTRAINT local_users_pkey PRIMARY KEY (id);


--
-- Name: mappings mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mappings
    ADD CONSTRAINT mappings_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: networks networks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.networks
    ADD CONSTRAINT networks_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: terms terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: action_logs_client_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX action_logs_client_index ON public.action_logs USING btree (client);


--
-- Name: action_logs_user_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX action_logs_user_index ON public.action_logs USING btree ("user");


--
-- Name: action_logs_uuid_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX action_logs_uuid_index ON public.action_logs USING btree (uuid);


--
-- Name: affiliations_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX affiliations_name_index ON public.affiliations USING btree (name);


--
-- Name: attrs_category_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attrs_category_index ON public.attrs USING btree (category);


--
-- Name: attrs_name_category_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attrs_name_category_index ON public.attrs USING btree (name, category);


--
-- Name: attrs_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attrs_name_index ON public.attrs USING btree (name);


--
-- Name: auth_logs_client_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_logs_client_index ON public.auth_logs USING btree (client);


--
-- Name: auth_logs_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_logs_type_index ON public.auth_logs USING btree (type);


--
-- Name: auth_logs_user_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_logs_user_index ON public.auth_logs USING btree ("user");


--
-- Name: auth_logs_uuid_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_logs_uuid_index ON public.auth_logs USING btree (uuid);


--
-- Name: dictionaries_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dictionaries_name_index ON public.dictionaries USING btree (name);


--
-- Name: groups_affiliation_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX groups_affiliation_id_index ON public.groups USING btree (affiliation_id);


--
-- Name: groups_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX groups_name_index ON public.groups USING btree (name);


--
-- Name: local_groups_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX local_groups_name_index ON public.local_groups USING btree (name);


--
-- Name: local_members_local_group_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX local_members_local_group_id_index ON public.local_members USING btree (local_group_id);


--
-- Name: local_members_local_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX local_members_local_user_id_index ON public.local_members USING btree (local_user_id);


--
-- Name: local_members_local_user_id_local_group_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX local_members_local_user_id_local_group_id_index ON public.local_members USING btree (local_user_id, local_group_id);


--
-- Name: local_users_local_group_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX local_users_local_group_id_index ON public.local_users USING btree (local_group_id);


--
-- Name: local_users_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX local_users_name_index ON public.local_users USING btree (name);


--
-- Name: mappings_attr_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mappings_attr_id_index ON public.mappings USING btree (attr_id);


--
-- Name: mappings_service_id_attr_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX mappings_service_id_attr_id_index ON public.mappings USING btree (service_id, attr_id);


--
-- Name: mappings_service_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mappings_service_id_index ON public.mappings USING btree (service_id);


--
-- Name: members_group_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX members_group_id_index ON public.members USING btree (group_id);


--
-- Name: members_user_id_group_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX members_user_id_group_id_index ON public.members USING btree (user_id, group_id);


--
-- Name: members_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX members_user_id_index ON public.members USING btree (user_id);


--
-- Name: networks_ip_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX networks_ip_index ON public.networks USING btree (ip);


--
-- Name: services_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX services_name_index ON public.services USING btree (name);


--
-- Name: terms_dictionary_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX terms_dictionary_id_index ON public.terms USING btree (dictionary_id);


--
-- Name: terms_term_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX terms_term_index ON public.terms USING btree (term);


--
-- Name: users_affiliation_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_affiliation_id_index ON public.users USING btree (affiliation_id);


--
-- Name: users_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_email_index ON public.users USING btree (email);


--
-- Name: users_group_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_group_id_index ON public.users USING btree (group_id);


--
-- Name: users_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_name_index ON public.users USING btree (name);


--
-- Name: groups groups_affiliation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_affiliation_id_fkey FOREIGN KEY (affiliation_id) REFERENCES public.affiliations(id) ON DELETE RESTRICT;


--
-- Name: local_members local_members_local_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_members
    ADD CONSTRAINT local_members_local_group_id_fkey FOREIGN KEY (local_group_id) REFERENCES public.local_groups(id) ON DELETE CASCADE;


--
-- Name: local_members local_members_local_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_members
    ADD CONSTRAINT local_members_local_user_id_fkey FOREIGN KEY (local_user_id) REFERENCES public.local_users(id) ON DELETE CASCADE;


--
-- Name: local_users local_users_local_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_users
    ADD CONSTRAINT local_users_local_group_id_fkey FOREIGN KEY (local_group_id) REFERENCES public.local_groups(id) ON DELETE SET NULL;


--
-- Name: mappings mappings_attr_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mappings
    ADD CONSTRAINT mappings_attr_id_fkey FOREIGN KEY (attr_id) REFERENCES public.attrs(id) ON DELETE CASCADE;


--
-- Name: mappings mappings_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mappings
    ADD CONSTRAINT mappings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE;


--
-- Name: members members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE CASCADE;


--
-- Name: members members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: terms terms_dictionary_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_dictionary_id_fkey FOREIGN KEY (dictionary_id) REFERENCES public.dictionaries(id) ON DELETE CASCADE;


--
-- Name: users users_affiliation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_affiliation_id_fkey FOREIGN KEY (affiliation_id) REFERENCES public.affiliations(id) ON DELETE RESTRICT;


--
-- Name: users users_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict jztKIliamzEmtrAU9sP3dWqd3wbacnX1r3d3Y7VOxExBEAKSknTJb8oMinxuxYd

SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('10000001001001_create_configs.rb'),
('10000001001002_create_networks.rb'),
('10000001002001_create_affiliations.rb'),
('10000001002002_create_groups.rb'),
('10000001002003_create_users.rb'),
('10000001002004_create_members.rb'),
('10000001003001_create_service.rb'),
('10000001004001_create_attrs.rb'),
('10000001004002_create_mappings.rb'),
('10000001005001_create_dictionaries.rb'),
('10000001005002_create_terms.rb'),
('10000002001001_create_action_logs.rb'),
('10000002002001_create_auth_logs.rb'),
('10000003001001_create_local_groups.rb'),
('10000003001002_create_local_users.rb'),
('10000003001003_create_local_members.rb');
