# Hanami
name: Hanami
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ["2.7"]
        node-version: ["16.x"]
    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: admin_password
          MARIADB_USER: admin
          MARIADB_PASSWORD: admin_password
          MARIADB_DATABASE: yuzakan_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up  Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Migrate DB
        run: bundle exec hanami db migrate
        env:
          HANAMI_ENV: test
      - name: Run build
        run: bundle exec rake build
      - name: Run tests
        run: bundle exec rake spec
