# Hanami
name: Hanami
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby-version: ["3.3"]
        node-version: ["22.x"]
    services:
      # mariadb:
      #   image: mariadb:10.11
      #   ports:
      #     - "3306:3306"
      #   env:
      #     MARIADB_ROOT_PASSWORD: password
      #     MARIADB_USER: yuzakan
      #     MARIADB_PASSWORD: password
      #     MARIADB_DATABASE: yuzakan_test
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: yuzakan_test
          POSTGRES_USER: yuzakan
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Migrate DB
        run: bundle exec hanami db migrate
        env:
          HANAMI_ENV: test
          DATABASE_URL: "postgres://yuzakan:password@localhost/yuzakan_test"
      - name: Compile assets
        run: bundle exec hanami assets compile
        env:
          HANAMI_ENV: test
          DATABASE_URL: "postgres://yuzakan:password@localhost/yuzakan_test"
      - name: Run spec tests
        run: bundle exec rake spec
        env:
          DATABASE_URL: "postgres://yuzakan:password@localhost/yuzakan_test"
      - name: Run js tests
        run: bundle exec rake js:test
