# Hanami
name: Hanami
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ["2.7"]
    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: admin_password
          MARIADB_USER: admin
          MARIADB_PASSWORD: admin_password
          MARIADB_DATABASE: yuzakan_test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Migrate DB
        run: bundle exec hanami db migrate
        env:
          HANAMI_ENV: test
      - name: Run tests
        run: bundle exec rake test
